config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'



  root to: 'static_pages#home'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get 'static_pages/home'
  get 'static_pages/contact'

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    validates :display_name, presence: true, length: { maximum: 55 }
    validates :email, presence: true, length: { maximum: 55 }
    validates :password, presence: true, length: { minimum: 6 }
    validates :email, uniqueness: true
    has_secure_password
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      log_in user
      redirect_to user
    else
      # Create an error message.
      flash[:danger] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end

  def destroy
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :display_name, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end


  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://use.fontawesome.com/caa7d91176.js"></script>
    <title><%= content_for?(:title) ? yield(:title) : "Tinker" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>


      <header class="header">
  <h1 class="headline">Tinker  <small>time</small></h1>
  <ul class="header-subnav">
    <section class="row-fluid">
        <nav class="span2">
            <ul class="side-nav nav nav-pills nav-stacked">
                <li><a href="#"><i class="fa fa-dashboard fa-2x"></i><br> <div class="wrd">Dashboard</div></a></li>
              <li><a href="http://localhost:3000"><i class="fa fa-home fa-2x"></i><br> <div class="wrd">Home</div></a></li>
              <li><a href="#"><i class="fa fa-envelope fa-2x"></i><br> <div class="wrd">Contact</div></a></li></ul>

        </nav>
    </section>
  </ul>
</header>
<div class="top-bar-right"><ul>
<li>
(Name + Email)
</li></ul></div>
<br>

     <div class="row">
       <div class="small-4 small-offset-2 columns">
      <% flash.each do |message_type, message| %>
      <div class="callout warning"<%= message_type %>><%= message %></div>
  <% end %>
     </div>
     </div>
    <%= yield %>

  </body>
</html>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
<br />
        <h5>Welcome!</h5>

        <div class="row">
          <div class="small-6 columns">
            <div class="callout ">
              <p><strong>Welcome</strong> If you're new, please sign up</p>
              <%=link_to("Sign up", {:controller => 'users', :action => 'new'}) %>
            </div>
          </div>
        </div>
        </div>

        <br />
<div class="row">
  <div class="small-6 columns">
    <div class="callout ">
      <p><strong>Been here before?</strong>Log in</p>
      <%=link_to('Log in', '/login' )%>
    </div>
  </div>
</div>

        <hr />
<!-- bottom of home page -->

app/views/users/_form.html.erb
<div class="row">
<%= form_for(@user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <div class="alert callout" data-closable>
        <h3><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>
        </div>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div class="field">
    <%= f.label :display_name %>
    <%= f.text_field :display_name %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Display name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.display_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Display name:</strong>
  <%= @user.display_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>